#com_user:
    #resource: "@ComUserBundle/Resources/config/routing.yml"
    #prefix:   /

com_daufin:
    resource: "@ComDaufinBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation    
# USER BUNDLE
Com_user:
    resource: "@ComUserBundle/Resources/config/routing.yml"
    prefix:   /

# CMS BUNDLE
#Com_cms:
#    resource: "@ComCmsBundle/Resources/config/routing.yml"
# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
# SONATA ADMIN BUNDLE
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix:   /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin

sonata_user_impersonating:
    pattern:  /
    defaults: { _controller: SonataPageBundle:Page:catchAll }
com_daufin_rest:
    resource: Com\DaufinBundle\Controller\RestPublicController
    prefix: /api
    type: rest
   