com_table_prix:
    path:     /
    defaults: { _controller: "ComDaufinBundle:TablePrix:index" }

com_table_prix_show:
    path:     /{id}/show
    defaults: { _controller: "ComDaufinBundle:TablePrix:show" }

com_table_prix_new:
    path:     /new
    defaults: { _controller: "ComDaufinBundle:TablePrix:new" }

com_table_prix_create:
    path:     /create
    defaults: { _controller: "ComDaufinBundle:TablePrix:create" }
    methods:  POST

com_table_prix_edit:
    path:     /{id}/edit
    defaults: { _controller: "ComDaufinBundle:TablePrix:edit" }

com_table_prix_update:
    path:     /{id}/update
    defaults: { _controller: "ComDaufinBundle:TablePrix:update" }
    methods:  [POST, PUT]

com_table_prix_delete:
    path:     /{id}/delete
    defaults: { _controller: "ComDaufinBundle:TablePrix:delete" }
    methods:  [POST, DELETE]
