com_voyage:
    path:     /
    defaults: { _controller: "ComDaufinBundle:Voyage:index" }

com_voyage_show:
    path:     /{id}/show
    defaults: { _controller: "ComDaufinBundle:Voyage:show" }

com_voyage_new:
    path:     /new
    defaults: { _controller: "ComDaufinBundle:Voyage:new" }

com_voyage_create:
    path:     /create
    defaults: { _controller: "ComDaufinBundle:Voyage:create" }
    methods:  POST

com_voyage_edit:
    path:     /{id}/edit
    defaults: { _controller: "ComDaufinBundle:Voyage:edit" }

com_voyage_update:
    path:     /{id}/update
    defaults: { _controller: "ComDaufinBundle:Voyage:update" }
    methods:  [POST, PUT]

com_voyage_delete:
    path:     /{id}/delete
    defaults: { _controller: "ComDaufinBundle:Voyage:delete" }
    methods:  [POST, DELETE]
